/**
 * CANONICAL EQUIPMENT CATALOG
 *
 * This is the single source of truth for what equipment appears in the
 * Equipment Catalog page. It is a curated list of gym equipment types.
 *
 * Pinecone is NOT used here. Pinecone is used in a separate flow to find
 * exercises that use a specific piece of equipment when a user taps on one.
 */

import type { EquipmentItem } from "./types";

export const EQUIPMENT_CATALOG: EquipmentItem[] = [
  {
    id: "dumbbell",
    name: "Dumbbells",
    category: "Free Weights",
    level: "beginner",
    equipment_type: "dumbbell",
    equipment_name: "Dumbbells",
    equipment_aliases: ["DB", "free weights", "hand weights"],
    primary_muscles: ["biceps", "triceps", "chest", "shoulders", "back"],
    secondary_muscles: ["core", "forearms"],
    image_urls: [],
    instructions: [
      "The most versatile free weight in the gym.",
      "Used for isolation exercises like curls and lateral raises, or compound movements like dumbbell press.",
      "Select a weight you can control for 8–12 reps with good form.",
    ],
  },
  {
    id: "barbell",
    name: "Barbell & Plates",
    category: "Free Weights",
    level: "intermediate",
    equipment_type: "barbell",
    equipment_name: "Olympic Barbell",
    equipment_aliases: ["bar", "olympic bar", "free weight bar"],
    primary_muscles: ["legs", "back", "chest", "shoulders"],
    secondary_muscles: ["core", "arms"],
    image_urls: [],
    instructions: [
      "The cornerstone of heavy compound lifting.",
      "Used for squats, deadlifts, bench press, and overhead press.",
      "Always use collars to secure the plates on both ends.",
    ],
  },
  {
    id: "cable",
    name: "Cable Crossover Machine",
    category: "Cables",
    level: "intermediate",
    equipment_type: "cable",
    equipment_name: "Dual Cable Crossover",
    equipment_aliases: ["cable machine", "cable station", "pulleys", "functional trainer"],
    primary_muscles: ["chest", "back", "shoulders", "arms"],
    secondary_muscles: ["core"],
    image_urls: [],
    instructions: [
      "Provides constant tension throughout the entire range of motion.",
      "Adjust the pulley height to target different muscle angles.",
      "Used for chest flys, tricep pushdowns, face pulls, and more.",
    ],
  },
  {
    id: "lat-pulldown-machine",
    name: "Lat Pulldown Machine",
    category: "Machines",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "Lat Pulldown Machine",
    equipment_aliases: ["pulldown machine", "cable pulldown"],
    primary_muscles: ["latissimus dorsi", "biceps"],
    secondary_muscles: ["rhomboids", "rear deltoids"],
    image_urls: [],
    instructions: [
      "The best machine for building a wide back.",
      "Adjust the knee pad so it holds you down firmly.",
      "Pull the bar to your upper chest and squeeze your lats at the bottom.",
    ],
  },
  {
    id: "leg-press-machine",
    name: "Leg Press Machine",
    category: "Machines",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "45-Degree Leg Press",
    equipment_aliases: ["sled press", "leg press"],
    primary_muscles: ["quadriceps", "glutes"],
    secondary_muscles: ["hamstrings", "calves"],
    image_urls: [],
    instructions: [
      "A great alternative to squats for building powerful legs.",
      "Place feet shoulder-width apart on the sled.",
      "Do not lock your knees at the top of the movement.",
    ],
  },
  {
    id: "smith-machine",
    name: "Smith Machine",
    category: "Machines",
    level: "intermediate",
    equipment_type: "machine",
    equipment_name: "Smith Machine",
    equipment_aliases: ["guided barbell", "smith rack"],
    primary_muscles: ["legs", "chest", "shoulders"],
    secondary_muscles: ["back", "arms"],
    image_urls: [],
    instructions: [
      "A barbell fixed on vertical steel rails for guided movement.",
      "Good for squats, bench press, and shoulder press with added stability.",
      "Rotate the bar to hook it onto the safety catches.",
    ],
  },
  {
    id: "leg-extension-machine",
    name: "Leg Extension Machine",
    category: "Machines",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "Seated Leg Extension",
    equipment_aliases: ["quad machine", "knee extension machine"],
    primary_muscles: ["quadriceps"],
    secondary_muscles: [],
    image_urls: [],
    instructions: [
      "An isolation machine specifically for the quadriceps.",
      "Adjust the back pad so your knees align with the machine's pivot point.",
      "Extend your legs fully and squeeze your quads at the top.",
    ],
  },
  {
    id: "leg-curl-machine",
    name: "Hamstring Curl Machine",
    category: "Machines",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "Lying Leg Curl",
    equipment_aliases: ["leg curl", "hamstring machine", "prone leg curl"],
    primary_muscles: ["hamstrings"],
    secondary_muscles: ["glutes", "calves"],
    image_urls: [],
    instructions: [
      "The primary isolation machine for the hamstrings.",
      "Lie face down with the pad positioned just above your heels.",
      "Curl your legs up toward your glutes and lower slowly.",
    ],
  },
  {
    id: "cable-row-machine",
    name: "Seated Cable Row",
    category: "Cables",
    level: "beginner",
    equipment_type: "cable",
    equipment_name: "Seated Cable Row Station",
    equipment_aliases: ["low pulley row", "cable back row", "seated row"],
    primary_muscles: ["rhomboids", "latissimus dorsi", "trapezius"],
    secondary_muscles: ["biceps", "rear deltoids"],
    image_urls: [],
    instructions: [
      "A fundamental machine for building a thick, strong back.",
      "Sit upright, brace your core, and pull the handle to your torso.",
      "Squeeze your shoulder blades together at the end of each rep.",
    ],
  },
  {
    id: "chest-press-machine",
    name: "Chest Press Machine",
    category: "Machines",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "Seated Chest Press",
    equipment_aliases: ["machine bench press", "pec press", "pectoral press"],
    primary_muscles: ["pectoralis major", "triceps"],
    secondary_muscles: ["anterior deltoids"],
    image_urls: [],
    instructions: [
      "A beginner-friendly alternative to the barbell bench press.",
      "Adjust the seat so the handles align with your mid-chest.",
      "Press forward smoothly and return with control.",
    ],
  },
  {
    id: "assisted-pullup-machine",
    name: "Assisted Pull-Up Machine",
    category: "Machines",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "Assisted Chin & Dip Station",
    equipment_aliases: ["gravitron", "assisted dip", "knee pad pull-up"],
    primary_muscles: ["latissimus dorsi", "biceps"],
    secondary_muscles: ["core", "triceps"],
    image_urls: [],
    instructions: [
      "Allows you to do pull-ups with a counterweight for assistance.",
      "The higher the weight selected, the more help you get.",
      "Great for building up to doing unassisted pull-ups.",
    ],
  },
  {
    id: "kettlebells",
    name: "Kettlebells",
    category: "Free Weights",
    level: "intermediate",
    equipment_type: "kettlebells",
    equipment_name: "Kettlebell",
    equipment_aliases: ["KB", "kettle bell"],
    primary_muscles: ["glutes", "hamstrings", "core", "shoulders"],
    secondary_muscles: ["back", "arms"],
    image_urls: [],
    instructions: [
      "A cast-iron weight with a handle used for dynamic movements.",
      "Perfect for swings, goblet squats, Turkish get-ups, and carries.",
      "Maintain a strong core and neutral spine during all exercises.",
    ],
  },
  {
    id: "resistance-bands",
    name: "Resistance Bands",
    category: "Free Weights",
    level: "beginner",
    equipment_type: "bands",
    equipment_name: "Resistance Bands",
    equipment_aliases: ["bands", "elastic bands", "loop bands"],
    primary_muscles: ["glutes", "shoulders", "back", "arms"],
    secondary_muscles: ["core"],
    image_urls: [],
    instructions: [
      "Lightweight elastic bands that provide resistance.",
      "The further you stretch them, the greater the resistance.",
      "Excellent for warming up, mobility work, and assisted exercises.",
    ],
  },
  {
    id: "ab-crunch-machine",
    name: "Abdominal Crunch Machine",
    category: "Machines",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "Seated Ab Crunch Machine",
    equipment_aliases: ["ab machine", "core crunch machine"],
    primary_muscles: ["rectus abdominis"],
    secondary_muscles: ["obliques"],
    image_urls: [],
    instructions: [
      "An isolation machine for the core.",
      "Sit with your arms behind the pads and crunch your torso forward.",
      "Focus on squeezing your abs, not pulling with your neck.",
    ],
  },
  {
    id: "treadmill",
    name: "Treadmill",
    category: "Cardio",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "Motorized Treadmill",
    equipment_aliases: ["running machine", "cardio machine"],
    primary_muscles: ["quadriceps", "hamstrings", "calves", "glutes"],
    secondary_muscles: ["core"],
    image_urls: [],
    instructions: [
      "A conveyor belt machine for walking, jogging, or running indoors.",
      "Use the incline setting to simulate hill walking and increase intensity.",
      "Always use the safety clip in case of a fall.",
    ],
  },
  {
    id: "stationary-bike",
    name: "Stationary Bike",
    category: "Cardio",
    level: "beginner",
    equipment_type: "machine",
    equipment_name: "Upright / Recumbent Bike",
    equipment_aliases: ["exercise bike", "spin bike", "cycling machine"],
    primary_muscles: ["quadriceps", "hamstrings", "calves", "glutes"],
    secondary_muscles: ["core"],
    image_urls: [],
    instructions: [
      "Low-impact cardio that is easy on the joints.",
      "Adjust the seat height so your leg has a slight bend at the bottom of the pedal stroke.",
      "Use resistance settings to increase the challenge.",
    ],
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    category: "Cardio",
    level: "intermediate",
    equipment_type: "machine",
    equipment_name: "Ergometer / Rowing Erg",
    equipment_aliases: ["erg", "concept 2 rower", "rowing erg", "rower"],
    primary_muscles: ["back", "legs", "core"],
    secondary_muscles: ["arms", "shoulders"],
    image_urls: [],
    instructions: [
      "A full-body cardio machine that works 86% of your muscles.",
      "The correct stroke sequence is: legs, body, arms — then reverse.",
      "Avoid hunching your back. Maintain an upright, engaged posture.",
    ],
  },
  {
    id: "ez-curl-bar",
    name: "EZ Curl Bar",
    category: "Free Weights",
    level: "beginner",
    equipment_type: "e-z curl bar",
    equipment_name: "EZ Curl Bar",
    equipment_aliases: ["ez bar", "curl bar", "zigzag bar"],
    primary_muscles: ["biceps", "triceps"],
    secondary_muscles: ["forearms"],
    image_urls: [],
    instructions: [
      "A W-shaped barbell that reduces wrist strain during curls.",
      "Better for the wrists than a straight barbell for arm exercises.",
      "Commonly used for barbell curls and skull crushers.",
    ],
  },
  {
    id: "pull-up-bar",
    name: "Pull-Up Bar",
    category: "Bodyweight",
    level: "intermediate",
    equipment_type: "body only",
    equipment_name: "Pull-Up / Chin-Up Bar",
    equipment_aliases: ["chinup bar", "chin up bar", "pull up station"],
    primary_muscles: ["latissimus dorsi", "biceps"],
    secondary_muscles: ["core", "rear deltoids"],
    image_urls: [],
    instructions: [
      "A fixed horizontal bar for bodyweight upper body pulling exercises.",
      "Overhand grip = pull-up (wider back). Underhand grip = chin-up (more biceps).",
      "Use a resistance band looped over the bar for assistance if needed.",
    ],
  },
  {
    id: "exercise-ball",
    name: "Exercise Ball",
    category: "Bodyweight",
    level: "beginner",
    equipment_type: "exercise ball",
    equipment_name: "Swiss / Stability Ball",
    equipment_aliases: ["swiss ball", "stability ball", "yoga ball", "balance ball"],
    primary_muscles: ["core", "back"],
    secondary_muscles: ["glutes", "chest"],
    image_urls: [],
    instructions: [
      "An inflatable ball used to add instability and challenge your core.",
      "Used for ball crunches, wall squats, dumbbell press, and stretching.",
      "Inflate so it is firm but still has a slight give when pressed.",
    ],
  },
];

/**
 * Each catalog item uses a representative image from the pinned exercise
 * dataset mirrored into GCS by the RAG ingestion job.
 */
export const EQUIPMENT_IMAGE_PATHS: Record<string, string> = {
  dumbbell: "Alternate_Incline_Dumbbell_Curl/0.jpg",
  barbell: "Barbell_Bench_Press_-_Medium_Grip/0.jpg",
  cable: "Cable_Crossover/0.jpg",
  "lat-pulldown-machine": "Full_Range-Of-Motion_Lat_Pulldown/0.jpg",
  "leg-press-machine": "Leg_Press/0.jpg",
  "smith-machine": "Smith_Machine_Bench_Press/0.jpg",
  "leg-extension-machine": "Leg_Extensions/0.jpg",
  "leg-curl-machine": "Lying_Leg_Curls/0.jpg",
  "cable-row-machine": "Seated_Cable_Rows/0.jpg",
  "chest-press-machine": "Leverage_Chest_Press/0.jpg",
  "assisted-pullup-machine": "Band_Assisted_Pull-Up/0.jpg",
  kettlebells: "Advanced_Kettlebell_Windmill/0.jpg",
  "resistance-bands": "Band_Pull_Apart/0.jpg",
  "ab-crunch-machine": "Ab_Crunch_Machine/0.jpg",
  treadmill: "Running_Treadmill/0.jpg",
  "stationary-bike": "Bicycling_Stationary/0.jpg",
  "rowing-machine": "Rowing_Stationary/0.jpg",
  "ez-curl-bar": "Close-Grip_EZ_Bar_Curl/0.jpg",
  "pull-up-bar": "Wide-Grip_Rear_Pull-Up/0.jpg",
  "exercise-ball": "Exercise_Ball_Crunch/0.jpg",
};
