steps:
  - id: Build production container
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --cache-from ${_IMAGE_URI} \
          --build-arg FITSPARK_RUNTIME_CONFIG_JSON="$$FITSPARK_RUNTIME_CONFIG_JSON" \
          --tag ${_IMAGE_URI} \
          -f infra/app/Dockerfile \
          .
    secretEnv: ['FITSPARK_RUNTIME_CONFIG_JSON']

  - id: Push production container
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE_URI}

  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - run
      - deploy
      - fit-spark
      - --image=${_IMAGE_URI}
      - --region=us-central1
      - --project=${PROJECT_ID}
      - --quiet

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/fitspark-runtime-config/versions/latest
      env: 'FITSPARK_RUNTIME_CONFIG_JSON'

images:
  - ${_IMAGE_URI}

serviceAccount: projects/${PROJECT_ID}/serviceAccounts/fit-spark-build@${PROJECT_ID}.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
